# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-15 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecatmodel',
            name='is_show',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='is_show',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否前端显示'),
        ),
    ]
