# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-16 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_articlecat_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecat',
            name='cat_image',
            field=models.ImageField(blank=True, default='', upload_to='cat/%Y/%m%d', verbose_name='分类图片'),
        ),
    ]
