# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-15 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190415_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleModel',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='ArticleCatModel',
            new_name='ArticleCat',
        ),
    ]
